# Generated by Django 5.2.7 on 2025-10-23 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('yoga', 'Yoga'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('muay_thai', 'Muay Thai'), ('boxing', 'Boxing'), ('ice_skating', 'Ice Skating')], max_length=20)),
                ('class_name', models.CharField(max_length=200)),
                ('is_by_appointment', models.BooleanField(default=False)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes_teaching', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
