# Generated by Django 5.2.6 on 2025-10-26 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='home_search.class')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('class_item', 'user')},
            },
        ),
    ]
