# Generated by Django 5.2.7 on 2025-10-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
