# Generated by Django 5.2.7 on 2025-10-24 11:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_details', '0002_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classdetails',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='class_images/'),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('class_details', 'user')},
        ),
    ]
