# Generated by Django 5.2.7 on 2025-10-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='User height in centimeters (80–250).', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='User weight in kilograms (25.00–300.00).', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='handle',
            field=models.SlugField(help_text='3–20 chars: a–z, 0–9, underscore, dot', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
