# Generated by Django 5.2.6 on 2025-10-26 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='phone_number',
            field=models.IntegerField(max_length=20),
        ),
    ]
