# Generated by Django 5.2.6 on 2025-10-24 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date_blog', models.DateField()),
                ('time_blog', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date', 'id'],
                'indexes': [models.Index(fields=['user', 'date'], name='main_person_user_id_458b8d_idx')],
            },
        ),
    ]
