# Generated by Django 5.2.7 on 2025-10-23 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('YOGA', 'Yoga'), ('PILATES', 'Pilates'), ('BOXING', 'Boxing'), ('MUAYTHAI', 'Muay Thai'), ('DANCE', 'Dance'), ('ICE_SKATING', 'Ice Skating')], max_length=20)),
                ('instructor', models.CharField(max_length=120)),
                ('starts_at', models.DateTimeField()),
                ('location_city', models.CharField(max_length=80)),
                ('location_address', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=16)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('popularity_score', models.IntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('instructor', 'starts_at', 'location_address'), name='unique_class_instance')],
            },
        ),
    ]
