# Generated by Django 5.2.6 on 2025-10-26 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('yoga', 'Yoga'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('boxing', 'Boxing'), ('muaythai', 'Muaythai'), ('ice-skating', 'Ice Skating')], db_index=True, max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('image_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
