# Generated by Django 5.2.7 on 2025-10-23 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='class',
            name='unique_class_instance',
        ),
        migrations.RemoveField(
            model_name='class',
            name='booked_count',
        ),
        migrations.RemoveField(
            model_name='class',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='class',
            name='location_address',
        ),
        migrations.RemoveField(
            model_name='class',
            name='location_city',
        ),
        migrations.RemoveField(
            model_name='class',
            name='popularity_score',
        ),
        migrations.RemoveField(
            model_name='class',
            name='starts_at',
        ),
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('Yoga', 'Yoga'), ('Pilates', 'Pilates'), ('Dance', 'Dance'), ('Boxing', 'Boxing'), ('Muaythai', 'Muaythai'), ('Ice', 'Ice')], max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
