# Generated by Django 5.2.7 on 2025-10-26 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('home_search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_classes', to='accounts.user'),
        ),
    ]
