# Generated by Django 5.1.3 on 2025-10-25 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='datetime',
            field=models.CharField(blank=True, max_length=120, verbose_name='DATE & TIME'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='class',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='class_pics/'),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=200, verbose_name='CLASS NAME'),
        ),
    ]
