# Generated by Django 5.1.3 on 2025-10-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0002_class_datetime_class_instructor_class_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
