# Generated by Django 5.2.7 on 2025-10-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0002_remove_class_unique_class_instance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('boxing', 'Boxing'), ('muaythai', 'Muaythai'), ('ice-skating', 'Ice Skating')], max_length=20),
        ),
    ]
