# Generated by Django 5.2.7 on 2025-10-24 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0003_alter_class_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='date_time',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='class',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='instructor',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
