# Generated by Django 5.1.3 on 2025-10-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0003_alter_class_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='class',
            name='picture',
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
