# Generated by Django 5.2.7 on 2025-10-24 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0005_class_owner_alter_class_category_alter_class_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='category',
            field=models.CharField(choices=[('yoga', 'Yoga'), ('pilates', 'Pilates'), ('dance', 'Dance'), ('boxing', 'Boxing'), ('muaythai', 'Muaythai'), ('ice-skating', 'Ice Skating')], db_index=True, max_length=50),
        ),
    ]
