# Generated by Django 5.2.7 on 2025-10-24 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_search', '0006_alter_class_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='class',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='class',
            name='location',
        ),
        migrations.AlterField(
            model_name='class',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
