import os
from dotenv import load_dotenv
# Load environment variables from .env file
load_dotenv()
"""
Django settings for ReServe project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'accounts.User'
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-87%f6#yh8av!o9h45#vy)8ju0#zx0h(a+32c8-q=&o2f@z34&3'

PRODUCTION = os.getenv('PRODUCTION', 'False').lower() == 'true'
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = not PRODUCTION

ALLOWED_HOSTS = ["localhost", "127.0.0.1", "khayru-rafa-reserve.pbp.cs.ui.ac.id"]

CSRF_TRUSTED_ORIGINS = [
    "https://khayru-rafa-reserve.pbp.cs.ui.ac.id",
]

if DEBUG:
    CSRF_TRUSTED_ORIGINS += [
        "http://localhost:8000",
        "http://127.0.0.1:8000",
        "http://localhost:52173",  # <-- add your flutter web port here
        "http://localhost:52680",  # <-- add your flutter web port here
    ]


INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'main',
    'accounts',
    'home_search',
    'blog',
    'PersonalGoals',
    'product_details',
    'checkout',
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',

]

ROOT_URLCONF = 'ReServe.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

WSGI_APPLICATION = 'ReServe.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database configuration
if PRODUCTION:
    # Production: use PostgreSQL with credentials from environment variables
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME'),
            'USER': os.getenv('DB_USER'),
            'PASSWORD': os.getenv('DB_PASSWORD'),
            'HOST': os.getenv('DB_HOST'),
            'PORT': os.getenv('DB_PORT'),
            'OPTIONS': {
                'options': f"-c search_path={os.getenv('SCHEMA', 'public')}"
            }
        }
    }
else:
    # Development: use SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

CORS_ALLOW_CREDENTIALS = True

if DEBUG:
    # Allow all origins for local development (Flutter uses dynamic ports)
    CORS_ALLOW_ALL_ORIGINS = True
    
    # Explicitly allow regex patterns for localhost and 127.0.0.1
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^http:\/\/localhost:\d+$",
        r"^http:\/\/127\.0\.0\.1:\d+$",
        r"^http:\/\/[:0-9a-fA-F]+$",  # IPv6
    ]
else:
    # Production: usually no need to allow any browser origins,
    # unless you host a separate frontend domain that calls this backend.
    CORS_ALLOWED_ORIGINS = [
        # Example (ONLY if needed):
        "https://khayru-rafa-reserve.pbp.cs.ui.ac.id",
    ]

# Session and Authentication Configuration
SESSION_COOKIE_HTTPONLY = False  # Allow client to access session cookie
SESSION_COOKIE_SAMESITE = None  # Allow credentials in cross-origin requests
SESSION_COOKIE_SECURE = False  # Allow over HTTP in development
CSRF_COOKIE_HTTPONLY = False  # Allow client to read CSRF token
CSRF_COOKIE_SAMESITE = None  # Allow credentials in cross-origin requests
CSRF_COOKIE_SECURE = False  # Allow over HTTP in development

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Auth redirects
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "post_login"
LOGOUT_REDIRECT_URL = "login"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / "static"  # or os.path.join(BASE_DIR, "staticfiles")

# STATICFILES_DIRS — source/static locations you edit during development
STATICFILES_DIRS = [
    BASE_DIR / "static",  # do NOT include STATIC_ROOT here
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "profile_view"
LOGOUT_REDIRECT_URL = "login"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
